# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

# Root composition only. Human-authored policy lives in catalog/; modules compile it into
# GitHub resources. Authentication is provided through short-lived GITHUB_TOKEN credentials
# generated by the workflow and is never a Terraform input or saved-plan value.
module "catalog" {
  source       = "./modules/catalog"
  catalog_path = "${path.module}/catalog"
}

locals {
  repositories            = module.catalog.repositories
  teams                   = module.catalog.teams
  team_access             = module.catalog.team_access
  environments            = module.catalog.environments
  repository_environments = { for name, cfg in module.catalog.repositories : name => cfg.environments }
  dr_evidence_environment_variables_raw = try(
    var.ci_variables["github-config"]["DR_EVIDENCE_ENVIRONMENT_VARIABLES"],
    "",
  )
  dr_evidence_environment_variables = local.dr_evidence_environment_variables_raw == "" ? tomap({}) : tomap(
    jsondecode(local.dr_evidence_environment_variables_raw)
  )
}

module "organization" {
  source = "./modules/organization"

  organization  = var.organization
  billing_email = var.billing_email
  # Organization webhooks are deliberately disabled until an audited endpoint and
  # secret-delivery path exist. No HMAC secret is serialized into Terraform plans/state.
  webhook_url    = ""
  webhook_secret = ""
  # Keep the retired root input referenced so Terraform evaluates its fail-closed
  # compatibility validation and tflint can verify that no dead input remains. The
  # validation requires this map to be empty; the catalog is the sole authority.
  app_scopes = merge(
    var.app_scopes,
    { for slug, app in module.catalog.github_apps : slug => app.repositories },
  )
}

module "teams" {
  source = "./modules/teams"

  teams                   = local.teams
  review_assignment_teams = toset(["legal", "platform", "security"])
  idp_export_path         = "${path.module}/idp/team-members.json"
}

module "repositories" {
  source = "./modules/repositories"

  repositories                      = local.repositories
  custom_properties                 = module.catalog.custom_properties
  team_access                       = local.team_access
  team_ids                          = module.teams.team_ids
  environments                      = local.environments
  repository_environments           = local.repository_environments
  environment_project_ids           = var.environment_project_ids
  dr_evidence_environment_variables = local.dr_evidence_environment_variables
  ci_variables                      = var.ci_variables
}

module "runner_groups" {
  source = "./modules/runner-groups"

  runner_groups  = module.catalog.runner_groups
  repository_ids = module.repositories.repository_ids
}

module "rulesets" {
  source = "./modules/rulesets"

  security_team_id       = tonumber(module.teams.team_ids["security"])
  legal_team_id          = tonumber(module.teams.team_ids["legal"])
  platform_team_id       = tonumber(module.teams.team_ids["platform"])
  infrastructure_team_id = tonumber(module.teams.team_ids["infrastructure"])
  release_team_id        = tonumber(module.teams.team_ids["release"])
  dot_github_repo_id     = module.repositories.repository_ids[".github"]

  rulesets              = module.catalog.rulesets
  repositories          = local.repositories
  enforcement_overrides = var.ruleset_enforcement_overrides
  release_tag_creation_control_qualified = (
    module.catalog.governance_activation.gates.release_tag_creation_control_qualified == "qualified"
  )
  release_signer_identity_qualified = (
    module.catalog.governance_activation.gates.release_signer_identity_qualified == "qualified"
  )
  github_config_verdict_observed = (
    module.catalog.governance_activation.gates.github_config_verdict_observed == "qualified"
  )

  # Custom-property-targeted rulesets must not race repository/property creation.
  depends_on = [module.repositories]
}

module "policies" {
  source = "./modules/policies"

  organization            = var.organization
  actions_policy          = module.catalog.actions_policy
  oidc_policy             = module.catalog.oidc_policy
  managed_repository_ids  = module.repositories.repository_ids
  wif_pool_project_number = var.wif_pool_project_number
  artifact_registry_host  = var.artifact_registry_host
}
