# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

---
development:
  wait_timer: 0
  reviewer_teams: []
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: false
  project_required: true
scratch:
  wait_timer: 0
  reviewer_teams:
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
staging:
  wait_timer: 0
  reviewer_teams:
    - platform
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: true
production:
  wait_timer: 10
  reviewer_teams:
    - platform
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: true
plan:
  wait_timer: 0
  reviewer_teams:
    - infrastructure
    - bootstrap-reviewers
  protected_branches: false
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
governance:
  wait_timer: 5
  reviewer_teams:
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
bootstrap:
  wait_timer: 10
  reviewer_teams:
    - infrastructure
    - security
    - bootstrap-reviewers
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
bootstrap-recovery-read:
  wait_timer: 0
  reviewer_teams:
    - infrastructure
    - security
    - bootstrap-reviewers
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
release:
  wait_timer: 5
  reviewer_teams:
    - release
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
workflow-release-platform:
  wait_timer: 0
  reviewer_teams:
    - platform
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
workflow-release-security:
  wait_timer: 0
  reviewer_teams:
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
repository-observability:
  wait_timer: 0
  reviewer_teams: []
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: false
  project_required: false
repository-maintenance:
  wait_timer: 5
  reviewer_teams:
    - platform
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
break-glass:
  wait_timer: 0
  reviewer_teams:
    - security
  protected_branches: true
  custom_branch_policies: false
  prevent_self_review: true
  project_required: false
